import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-memory',
  templateUrl: './memory.component.html',
  styleUrls: ['./memory.component.scss']
})
export class MemoryComponent implements OnInit {

  constructor() { }
  matrix: any = {}
  imgUrls = [
    "assets/memory/accessibility.svg",
    "assets/memory/add.svg",
    "assets/memory/add-circle.svg",
    "assets/memory/airplane.svg",
    "assets/memory/alarm.svg",
    "assets/memory/albums.svg",
    "assets/memory/alert.svg",
    "assets/memory/alert-circle.svg",
    "assets/memory/american-football.svg",
    "assets/memory/analytics.svg",
    "assets/memory/aperture.svg",
    "assets/memory/apps.svg",
    "assets/memory/archive.svg",
    "assets/memory/arrow-back.svg",
    "assets/memory/arrow-back-circle.svg",
    "assets/memory/arrow-down.svg",
    "assets/memory/arrow-down-circle.svg",
    "assets/memory/arrow-forward.svg",
    "assets/memory/arrow-forward-circle.svg",
    "assets/memory/arrow-redo.svg",
    "assets/memory/arrow-redo-circle.svg",
    "assets/memory/arrow-undo.svg",
    "assets/memory/arrow-undo-circle.svg",
    "assets/memory/arrow-up.svg",
    "assets/memory/arrow-up-circle.svg",
    "assets/memory/at.svg",
    "assets/memory/at-circle.svg",
    "assets/memory/attach.svg",
    "assets/memory/backspace.svg",
    "assets/memory/bag.svg",
    "assets/memory/bag-add.svg",
    "assets/memory/bag-check.svg",
    "assets/memory/bag-handle.svg",
    "assets/memory/bag-remove.svg",
    "assets/memory/balloon.svg",
    "assets/memory/ban.svg",
    "assets/memory/bandage.svg",
    "assets/memory/barbell.svg",
    "assets/memory/bar-chart.svg",
    "assets/memory/barcode.svg",
    "assets/memory/baseball.svg",
    "assets/memory/basket.svg",
    "assets/memory/basketball.svg",
    "assets/memory/battery-charging.svg",
    "assets/memory/battery-dead.svg",
    "assets/memory/battery-full.svg",
    "assets/memory/battery-half.svg",
    "assets/memory/beaker.svg",
    "assets/memory/bed.svg",
    "assets/memory/beer.svg",
    "assets/memory/bicycle.svg",
    "assets/memory/bluetooth.svg",
    "assets/memory/boat.svg",
    "assets/memory/body.svg",
    "assets/memory/bonfire.svg",
    "assets/memory/book.svg",
    "assets/memory/bookmark.svg",
    "assets/memory/bookmarks.svg",
    "assets/memory/bowling-ball.svg",
    "assets/memory/briefcase.svg",
    "assets/memory/browsers.svg",
    "assets/memory/brush.svg",
    "assets/memory/bug.svg",
    "assets/memory/build.svg",
    "assets/memory/bulb.svg",
    "assets/memory/bus.svg",
    "assets/memory/business.svg",
    "assets/memory/cafe.svg",
    "assets/memory/calculator.svg",
    "assets/memory/calendar.svg",
    "assets/memory/calendar-clear.svg",
    "assets/memory/calendar-number.svg",
    "assets/memory/call.svg",
    "assets/memory/camera.svg",
    "assets/memory/camera-reverse.svg",
    "assets/memory/car.svg",
    "assets/memory/card.svg",
    "assets/memory/caret-back.svg",
    "assets/memory/caret-back-circle.svg",
    "assets/memory/caret-down.svg",
    "assets/memory/caret-down-circle.svg",
    "assets/memory/caret-forward.svg",
    "assets/memory/caret-forward-circle.svg",
    "assets/memory/caret-up.svg",
    "assets/memory/caret-up-circle.svg",
    "assets/memory/car-sport.svg",
    "assets/memory/cart.svg",
    "assets/memory/cash.svg",
    "assets/memory/cellular.svg",
    "assets/memory/chatbox.svg",
    "assets/memory/chatbox-ellipses.svg",
    "assets/memory/chatbubble.svg",
    "assets/memory/chatbubble-ellipses.svg",
    "assets/memory/chatbubbles.svg",
    "assets/memory/checkbox.svg",
    "assets/memory/checkmark.svg",
    "assets/memory/checkmark-circle.svg",
    "assets/memory/checkmark-done.svg",
    "assets/memory/checkmark-done-circle.svg",
    "assets/memory/chevron-back.svg",
    "assets/memory/chevron-back-circle.svg",
    "assets/memory/chevron-down.svg",
    "assets/memory/chevron-down-circle.svg",
    "assets/memory/chevron-forward.svg",
    "assets/memory/chevron-forward-circle.svg",
    "assets/memory/chevron-up.svg",
    "assets/memory/chevron-up-circle.svg",
    "assets/memory/clipboard.svg",
    "assets/memory/close.svg",
    "assets/memory/close-circle.svg",
    "assets/memory/cloud.svg",
    "assets/memory/cloud-circle.svg",
    "assets/memory/cloud-done.svg",
    "assets/memory/cloud-download.svg",
    "assets/memory/cloud-offline.svg",
    "assets/memory/cloud-upload.svg",
    "assets/memory/cloudy.svg",
    "assets/memory/cloudy-night.svg",
    "assets/memory/code.svg",
    "assets/memory/code-download.svg",
    "assets/memory/code-slash.svg",
    "assets/memory/code-working.svg",
    "assets/memory/cog.svg",
    "assets/memory/color-fill.svg",
    "assets/memory/color-filter.svg",
    "assets/memory/color-palette.svg",
    "assets/memory/color-wand.svg",
    "assets/memory/compass.svg",
    "assets/memory/construct.svg",
    "assets/memory/contract.svg",
    "assets/memory/contrast.svg",
    "assets/memory/copy.svg",
    "assets/memory/create.svg",
    "assets/memory/crop.svg",
    "assets/memory/cube.svg",
    "assets/memory/cut.svg",
    "assets/memory/desktop.svg",
    "assets/memory/diamond.svg",
    "assets/memory/dice.svg",
    "assets/memory/disc.svg",
    "assets/memory/document.svg",
    "assets/memory/document-attach.svg",
    "assets/memory/document-lock.svg",
    "assets/memory/documents.svg",
    "assets/memory/document-text.svg",
    "assets/memory/download.svg",
    "assets/memory/duplicate.svg",
    "assets/memory/ear.svg",
    "assets/memory/earth.svg",
    "assets/memory/easel.svg",
    "assets/memory/egg.svg",
    "assets/memory/ellipse.svg",
    "assets/memory/ellipsis-horizontal.svg",
    "assets/memory/ellipsis-horizontal-circle.svg",
    "assets/memory/ellipsis-vertical.svg",
    "assets/memory/ellipsis-vertical-circle.svg",
    "assets/memory/enter.svg",
    "assets/memory/exit.svg",
    "assets/memory/expand.svg",
    "assets/memory/extension-puzzle.svg",
    "assets/memory/eye.svg",
    "assets/memory/eyedrop.svg",
    "assets/memory/eye-off.svg",
    "assets/memory/fast-food.svg",
    "assets/memory/female.svg",
    "assets/memory/file-tray.svg",
    "assets/memory/file-tray-full.svg",
    "assets/memory/file-tray-stacked.svg",
    "assets/memory/film.svg",
    "assets/memory/filter.svg",
    "assets/memory/filter-circle.svg",
    "assets/memory/finger-print.svg",
    "assets/memory/fish.svg",
    "assets/memory/fitness.svg",
    "assets/memory/flag.svg",
    "assets/memory/flame.svg",
    "assets/memory/flash.svg",
    "assets/memory/flashlight.svg",
    "assets/memory/flash-off.svg",
    "assets/memory/flask.svg",
    "assets/memory/flower.svg",
    "assets/memory/folder.svg",
    "assets/memory/folder-open.svg",
    "assets/memory/football.svg",
    "assets/memory/footsteps.svg",
    "assets/memory/funnel.svg",
    "assets/memory/game-controller.svg",
    "assets/memory/gift.svg",
    "assets/memory/git-branch.svg",
    "assets/memory/git-commit.svg",
    "assets/memory/git-compare.svg",
    "assets/memory/git-merge.svg",
    "assets/memory/git-network.svg",
    "assets/memory/git-pull-request.svg",
    "assets/memory/glasses.svg",
    "assets/memory/globe.svg",
    "assets/memory/golf.svg",
    "assets/memory/grid.svg",
    "assets/memory/hammer.svg",
    "assets/memory/hand-left.svg",
    "assets/memory/hand-right.svg",
    "assets/memory/happy.svg",
    "assets/memory/hardware-chip.svg",
    "assets/memory/headset.svg",
    "assets/memory/heart.svg",
    "assets/memory/heart-circle.svg",
    "assets/memory/heart-dislike.svg",
    "assets/memory/heart-dislike-circle.svg",
    "assets/memory/heart-half.svg",
    "assets/memory/help.svg",
    "assets/memory/help-buoy.svg",
    "assets/memory/help-circle.svg",
    "assets/memory/home.svg",
    "assets/memory/hourglass.svg",
    "assets/memory/ice-cream.svg",
    "assets/memory/id-card.svg",
    "assets/memory/image.svg",
    "assets/memory/images.svg",
    "assets/memory/infinite.svg",
    "assets/memory/information.svg",
    "assets/memory/information-circle.svg",
    "assets/memory/invert-mode.svg",
    "assets/memory/journal.svg",
    "assets/memory/key.svg",
    "assets/memory/keypad.svg",
    "assets/memory/language.svg",
    "assets/memory/laptop.svg",
    "assets/memory/layers.svg",
    "assets/memory/leaf.svg",
    "assets/memory/library.svg",
    "assets/memory/link.svg",
    "assets/memory/list.svg",
    "assets/memory/list-circle.svg",
    "assets/memory/locate.svg",
    "assets/memory/location.svg",
    "assets/memory/lock-closed.svg",
    "assets/memory/lock-open.svg",
    "assets/memory/log-in.svg",
    "assets/memory/logo-alipay.svg",
    "assets/memory/logo-amazon.svg",
    "assets/memory/logo-amplify.svg",
    "assets/memory/logo-android.svg",
    "assets/memory/logo-angular.svg",
    "assets/memory/logo-apple.svg",
    "assets/memory/logo-apple-appstore.svg",
    "assets/memory/logo-apple-ar.svg",
    "assets/memory/logo-behance.svg",
    "assets/memory/logo-bitbucket.svg",
    "assets/memory/logo-bitcoin.svg",
    "assets/memory/logo-buffer.svg",
    "assets/memory/logo-capacitor.svg",
    "assets/memory/logo-chrome.svg",
    "assets/memory/logo-closed-captioning.svg",
    "assets/memory/logo-codepen.svg",
    "assets/memory/logo-css3.svg",
    "assets/memory/logo-designernews.svg",
    "assets/memory/logo-deviantart.svg",
    "assets/memory/logo-discord.svg",
    "assets/memory/logo-docker.svg",
    "assets/memory/logo-dribbble.svg",
    "assets/memory/logo-dropbox.svg",
    "assets/memory/logo-edge.svg",
    "assets/memory/logo-electron.svg",
    "assets/memory/logo-euro.svg",
    "assets/memory/logo-facebook.svg",
    "assets/memory/logo-figma.svg",
    "assets/memory/logo-firebase.svg",
    "assets/memory/logo-firefox.svg",
    "assets/memory/logo-flickr.svg",
    "assets/memory/logo-foursquare.svg",
    "assets/memory/logo-github.svg",
    "assets/memory/logo-gitlab.svg",
    "assets/memory/logo-google.svg",
    "assets/memory/logo-google-playstore.svg",
    "assets/memory/logo-hackernews.svg",
    "assets/memory/logo-html5.svg",
    "assets/memory/logo-instagram.svg",
    "assets/memory/logo-ionic.svg",
    "assets/memory/logo-ionitron.svg",
    "assets/memory/logo-javascript.svg",
    "assets/memory/logo-laravel.svg",
    "assets/memory/logo-linkedin.svg",
    "assets/memory/logo-markdown.svg",
    "assets/memory/logo-mastodon.svg",
    "assets/memory/logo-medium.svg",
    "assets/memory/logo-microsoft.svg",
    "assets/memory/logo-nodejs.svg",
    "assets/memory/logo-no-smoking.svg",
    "assets/memory/logo-npm.svg",
    "assets/memory/logo-octocat.svg",
    "assets/memory/logo-paypal.svg",
    "assets/memory/logo-pinterest.svg",
    "assets/memory/logo-playstation.svg",
    "assets/memory/logo-pwa.svg",
    "assets/memory/logo-python.svg",
    "assets/memory/logo-react.svg",
    "assets/memory/logo-reddit.svg",
    "assets/memory/logo-rss.svg",
    "assets/memory/logo-sass.svg",
    "assets/memory/logo-skype.svg",
    "assets/memory/logo-slack.svg",
    "assets/memory/logo-snapchat.svg",
    "assets/memory/logo-soundcloud.svg",
    "assets/memory/logo-stackoverflow.svg",
    "assets/memory/logo-steam.svg",
    "assets/memory/logo-stencil.svg",
    "assets/memory/logo-tableau.svg",
    "assets/memory/logo-tiktok.svg",
    "assets/memory/logo-tumblr.svg",
    "assets/memory/logo-tux.svg",
    "assets/memory/logo-twitch.svg",
    "assets/memory/logo-twitter.svg",
    "assets/memory/logo-usd.svg",
    "assets/memory/log-out.svg",
    "assets/memory/logo-venmo.svg",
    "assets/memory/logo-vercel.svg",
    "assets/memory/logo-vimeo.svg",
    "assets/memory/logo-vk.svg",
    "assets/memory/logo-vue.svg",
    "assets/memory/logo-web-component.svg",
    "assets/memory/logo-wechat.svg",
    "assets/memory/logo-whatsapp.svg",
    "assets/memory/logo-windows.svg",
    "assets/memory/logo-wordpress.svg",
    "assets/memory/logo-xbox.svg",
    "assets/memory/logo-xing.svg",
    "assets/memory/logo-yahoo.svg",
    "assets/memory/logo-yen.svg",
    "assets/memory/logo-youtube.svg",
    "assets/memory/magnet.svg",
    "assets/memory/mail.svg",
    "assets/memory/mail-open.svg",
    "assets/memory/mail-unread.svg",
    "assets/memory/male.svg",
    "assets/memory/male-female.svg",
    "assets/memory/man.svg",
    "assets/memory/map.svg",
    "assets/memory/medal.svg",
    "assets/memory/medical.svg",
    "assets/memory/medkit.svg",
    "assets/memory/megaphone.svg",
    "assets/memory/menu.svg",
    "assets/memory/mic.svg",
    "assets/memory/mic-circle.svg",
    "assets/memory/mic-off.svg",
    "assets/memory/mic-off-circle.svg",
    "assets/memory/moon.svg",
    "assets/memory/move.svg",
    "assets/memory/musical-note.svg",
    "assets/memory/musical-notes.svg",
    "assets/memory/navigate.svg",
    "assets/memory/navigate-circle.svg",
    "assets/memory/newspaper.svg",
    "assets/memory/notifications.svg",
    "assets/memory/notifications-circle.svg",
    "assets/memory/notifications-off.svg",
    "assets/memory/notifications-off-circle.svg",
    "assets/memory/nuclear.svg",
    "assets/memory/nutrition.svg",
    "assets/memory/open.svg",
    "assets/memory/options.svg",
    "assets/memory/paper-plane.svg",
    "assets/memory/partly-sunny.svg",
    "assets/memory/pause.svg",
    "assets/memory/pause-circle.svg",
    "assets/memory/paw.svg",
    "assets/memory/pencil.svg",
    "assets/memory/people.svg",
    "assets/memory/people-circle.svg",
    "assets/memory/person.svg",
    "assets/memory/person-add.svg",
    "assets/memory/person-circle.svg",
    "assets/memory/person-remove.svg",
    "assets/memory/phone-landscape.svg",
    "assets/memory/phone-portrait.svg",
    "assets/memory/pie-chart.svg",
    "assets/memory/pin.svg",
    "assets/memory/pint.svg",
    "assets/memory/pizza.svg",
    "assets/memory/planet.svg",
    "assets/memory/play.svg",
    "assets/memory/play-back.svg",
    "assets/memory/play-back-circle.svg",
    "assets/memory/play-circle.svg",
    "assets/memory/play-forward.svg",
    "assets/memory/play-forward-circle.svg",
    "assets/memory/play-skip-back.svg",
    "assets/memory/play-skip-back-circle.svg",
    "assets/memory/play-skip-forward.svg",
    "assets/memory/play-skip-forward-circle.svg",
    "assets/memory/podium.svg",
    "assets/memory/power.svg",
    "assets/memory/pricetag.svg",
    "assets/memory/pricetags.svg",
    "assets/memory/print.svg",
    "assets/memory/prism.svg",
    "assets/memory/pulse.svg",
    "assets/memory/push.svg",
    "assets/memory/qr-code.svg",
    "assets/memory/radio.svg",
    "assets/memory/radio-button-off.svg",
    "assets/memory/radio-button-on.svg",
    "assets/memory/rainy.svg",
    "assets/memory/reader.svg",
    "assets/memory/receipt.svg",
    "assets/memory/recording.svg",
    "assets/memory/refresh.svg",
    "assets/memory/refresh-circle.svg",
    "assets/memory/reload.svg",
    "assets/memory/reload-circle.svg",
    "assets/memory/remove.svg",
    "assets/memory/remove-circle.svg",
    "assets/memory/reorder-four.svg",
    "assets/memory/reorder-three.svg",
    "assets/memory/reorder-two.svg",
    "assets/memory/repeat.svg",
    "assets/memory/resize.svg",
    "assets/memory/restaurant.svg",
    "assets/memory/return-down-back.svg",
    "assets/memory/return-down-forward.svg",
    "assets/memory/return-up-back.svg",
    "assets/memory/return-up-forward.svg",
    "assets/memory/ribbon.svg",
    "assets/memory/rocket.svg",
    "assets/memory/rose.svg",
    "assets/memory/sad.svg",
    "assets/memory/save.svg",
    "assets/memory/scale.svg",
    "assets/memory/scan.svg",
    "assets/memory/scan-circle.svg",
    "assets/memory/school.svg",
    "assets/memory/search.svg",
    "assets/memory/search-circle.svg",
    "assets/memory/send.svg",
    "assets/memory/server.svg",
    "assets/memory/settings.svg",
    "assets/memory/shapes.svg",
    "assets/memory/share.svg",
    "assets/memory/share-social.svg",
    "assets/memory/shield.svg",
    "assets/memory/shield-checkmark.svg",
    "assets/memory/shield-half.svg",
    "assets/memory/shirt.svg",
    "assets/memory/shuffle.svg",
    "assets/memory/skull.svg",
    "assets/memory/snow.svg",
    "assets/memory/sparkles.svg",
    "assets/memory/speedometer.svg",
    "assets/memory/square.svg",
    "assets/memory/star.svg",
    "assets/memory/star-half.svg",
    "assets/memory/stats-chart.svg",
    "assets/memory/stop.svg",
    "assets/memory/stop-circle.svg",
    "assets/memory/stopwatch.svg",
    "assets/memory/storefront.svg",
    "assets/memory/subway.svg",
    "assets/memory/sunny.svg",
    "assets/memory/swap-horizontal.svg",
    "assets/memory/swap-vertical.svg",
    "assets/memory/sync.svg",
    "assets/memory/sync-circle.svg",
    "assets/memory/tablet-landscape.svg",
    "assets/memory/tablet-portrait.svg",
    "assets/memory/telescope.svg",
    "assets/memory/tennisball.svg",
    "assets/memory/terminal.svg",
    "assets/memory/text.svg",
    "assets/memory/thermometer.svg",
    "assets/memory/thumbs-down.svg",
    "assets/memory/thumbs-up.svg",
    "assets/memory/thunderstorm.svg",
    "assets/memory/ticket.svg",
    "assets/memory/time.svg",
    "assets/memory/timer.svg",
    "assets/memory/today.svg",
    "assets/memory/toggle.svg",
    "assets/memory/trail-sign.svg",
    "assets/memory/train.svg",
    "assets/memory/transgender.svg",
    "assets/memory/trash.svg",
    "assets/memory/trash-bin.svg",
    "assets/memory/trending-down.svg",
    "assets/memory/trending-up.svg",
    "assets/memory/triangle.svg",
    "assets/memory/trophy.svg",
    "assets/memory/tv.svg",
    "assets/memory/videocam.svg",
    "assets/memory/videocam-off.svg",
    "assets/memory/volume-high.svg",
    "assets/memory/volume-low.svg",
    "assets/memory/volume-medium.svg",
    "assets/memory/volume-mute.svg",
    "assets/memory/volume-off.svg",
    "assets/memory/walk.svg",
    "assets/memory/wallet.svg",
    "assets/memory/warning.svg",
    "assets/memory/watch.svg",
    "assets/memory/water.svg",
    "assets/memory/wifi.svg",
    "assets/memory/wine.svg",
    "assets/memory/woman.svg",
  ]
  imgUse: string[] = []
  loaded = false
  timeout = 0;
  clicks = 0;
  acerts = 0;
  temps = 60;
  percentatge = 100;
  clicked = 0;

  ngOnInit(): void {
    this.generateMatrix()
  }

  showVictory = false;
  showLose = false;

  generateMatrix() {
    this.loaded = false
    this.showLose = false;
    this.showVictory = false;
    this.temps = 60;
    this.percentatge = 100;
    this.acerts = 0;
    this.clicks = 0;
    setTimeout(() => {
      this.imgUse = this.getImages();
      for (let i = 0; i < 6; i++) {
        this.matrix[i] = {}
        for (let j = 0; j < 4; j++) {
          let image =  this.imgUse[j%2+i*2]
          this.matrix[i][j] = {image: image,visible: false}
        }
      }
      for (let i = 0; i < 50; i++) {
        let j = Math.floor(Math.random() * (6))
        let k = Math.floor(Math.random() * (4))
        let jj= Math.floor(Math.random() * (6))
        let kk = Math.floor(Math.random() * (4))
        let fitxaTemp = this.matrix[jj][kk]
        this.matrix[jj][kk] = this.matrix[j][k]
        this.matrix[j][k] = fitxaTemp
      }
      console.log(this.matrix)
      this.loaded = true
      this.initPartida();
    }, this.timeout);
    this.timeout = 1100;
  }
  
  initPartida() {
    if (this.loaded && this.temps > 0 && !this.showVictory) {
      setTimeout(() => {
        if (!this.showVictory) {
          this.temps -= 1;
          this.initPartida();
        }
      }, 1000);
    } else if (this.temps == 0) {
      this.showLose = true;
      alert("Loose")
    } 
  }

  getImages() {
    let arr: string[] = []
    for (let i = 0; i < 12; i++) {
      let img = this.imgUrls[Math.floor(Math.random() * this.imgUrls.length)]
      if (!arr.includes(img)) {
        arr.push(img)
      } else {
        i--
      }
    }
    return arr
  }

  victory() {
    this.showVictory = true;
  }

  lose() {
    this.showLose = true;
  }

  click(value: any) {
    this.clicked += 1;
    if (value == 1) {
      this.acerts += 1 
    } 
    if (this.clicked%2 == 0) {
      this.clicks = this.clicks + 1
      this.clicked = 0
      this.percentatge = Math.trunc(this.acerts*100/this.clicks)
    }
    
    
  }

}
